### ISSUE TITLE
вынесите пожалуйста в конфиг адрес бота

### ISSUE THREAD

**Issue by MetaDone** [z00k/vkbotphp#1]
в файле /autoupdate.php 58 и следующие строки - в моменте получения сообщения прописано http://bot.mew.su/, из-за чего при установке называет себя Ларисой

**Comment by z00k** [comment]
Скорее всего вы не вписали ID своего бота из-за чего он и думает, что он - Лариса.

**Comment by z00k** [comment]
config.sample.php -> 14 строка

**Comment by MetaDone** [comment]
autoupdate.php
 $mes = file_get_contents('http://bot.mew.su/sp.php?session=' . $row['chatid'] . '&text=' . urlencode($vkmessage));
вот здесь привязка к http://bot.mew.su/, про нее говорил. После того как переписал адреса в файле на адрес, где лежит мой бот, все корректно заработало

**Comment by arnidan** [comment]
Я потиху переделываю. Потому что автор, скорее всего, несильно знаком с PHP

**Comment by z00k** [comment]
Ждите в новой версии массу исправлений и поддержку antigate.
