### ISSUE TITLE
Не могу подключить скрипт к бд.

### ISSUE THREAD

**Issue by oleg-rakitin** [z00k/vkbotphp#20]
Ввожу все правильно: http://prntscr.com/7pofba, но выдает, что не может подключиться: http://prntscr.com/7pofkq

**Comment by andreymukha** [comment]
Там же написано, что неизвестный хост MySQL сервера, видимо в IP ошибка, может просто localhost там написать?

**Comment by oleg-rakitin** [comment]
@andreymukha , ip я копирую, в принципе ошибки не может быть... "localhost" тоже пробовал писать, но результат такой же. Я хз в чем проблема, все скрипты также подключал обычно.

**Comment by andreymukha** [comment]
И с другими скриптами работает?

**Comment by oleg-rakitin** [comment]
@andreymukha , работает.

**Comment by andreymukha** [comment]
И работает с тем же MySQL сервером?

**Comment by z00k** [comment]
Нужно вводить данные без {}
т.е. mysqli_connect("192.168.0.1", "root"...
