### ISSUE TITLE
Беседы

### ISSUE THREAD

**Issue by vendelieu** [z00k/vkbotphp#21]
Добавьте поддержку бесед. Если добавить бота в беседу чтобы он отвечал по обращению к нему "Бот, Привет...итд". + Сейчас если его добавить и написать в беседе что-то(наважно что) то он начнеть спамить в лс

**Comment by m-derevyanko** [comment]
Серьезно? Ты код программы видел? У идиота-автора мозгов не хватит это сделать

**Comment by JunoReactor** [comment]
Не нравится, пиши свой, выкладывай сюда, а мы оценим, а автора дерьмом поливать не нужно.

**Comment by m-derevyanko** [comment]
@JunoReactor ты сначала законтрибьють хоть что-нибудь в своей жизни, потом будешь мне советы давать. Быдлокодер и представители потреблядства нашли друг друга.

Свободный доступ к гитхабу не повод выкладывать сюда всякий быдлошлак. Из-за идиота-автора подобный шлак разойдется тысячами тиражей, а такие как ты будут его по дороге в жопу целовать, попутно все присутствующие будут считать себя великими программистами.

Автору нужно не просто учиться писать код, но и почитать как его структурировать, изучить хотя бы азы ооп. ООП это вам не class foo{ function bar{} } блядь.

**Comment by petrozavodsky** [comment]
Ну так если будет лучшая альтернатива  то плохой библиотекой никто пользоваться не будет, хорошим решением будет всем недовольным собраться. И сделать форк или ещё лучше отдельный репозиторий и там уже писать нормальный Код

**Comment by JunoReactor** [comment]
Поддержка бесед была бы очень полезной, или как минимум автовыход из беседы, у моего бота уже почти 8500 друзей, ежедневно его кидают в беседы с тысячами сообщений, кинувшему в беседу летят тысячи строк спама, и при условии что бот параллельно общается с сотней людей, возникает капча.

**Comment by JunoReactor** [comment]
В общем если по простому то автовыход из беседы можно сделать так:
autoupdate.php
Примерно 32 строка...  
foreach ((array)$messages['response'] as $key => $value) {
        $uid = $value['uid'];
        $message = $value['body'];

```
    if( isset($value['chat_id']) ) {
        $messages = $vk->request('messages.removeChatUser', array(
            'chat_id' => $value['chat_id'],
            'uid' => BOT_ID
        ));

    }
```

.....
